name: run script index.py

on:
  schedule:
    - cron: '10 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run index.p
        env:
          TOFFEE_SECRET_KEY: ${{ secrets.TOFFEE_SECRET_KEY }}
          TOFFEE_HEADER1: ${{ secrets.TOFFEE_HEADER1 }}
          TOFFEE_HEADER2: ${{ secrets.TOFFEE_HEADER2 }}
          BDPROXY: ${{ secrets.BDPROXY }}
          TOFFEE_URL1: ${{ secrets.TOFFEE_URL1 }}
          TOFFEE_URL2: ${{ secrets.TOFFEE_URL2 }}
        
        run: python api/index.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Toffee Data updated!" --allow-empty)
         
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 

permissions:
  contents: write
